In [152]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [156]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [157]:
path = '/content/drive/MyDrive/데이터분석프로젝트/강서구 공모전/데이터/전처리_데이터/'

In [158]:
df_merge = pd.read_csv(path + '강서구편의점_통합데이터.csv')
df_list = pd.read_csv(path + '강서구편의점_목록.csv')

In [160]:
display(df_merge)
display(df_list)

SyntaxError: ignored

In [90]:
total_df = pd.merge(df_merge,df_list, on='도로명주소')
total_con = total_df[['상호명_x','지점명_x','단차/계단','확인불가','도로명주소','소재지면적','위도','경도']]
change_df = total_df[total_df['확인불가']==3][['상호명_y','지점명_y','도로명주소']]

In [91]:
total_con.columns = ['상호명','지점명','단차/계단여부','확인가능여부','도로명주소','소재지면적','위도','경도']

In [92]:
group_1_ad = ['서울특별시 강서구 양천로 50','서울특별시 강서구 방화대로45길 52','서울특별시 강서구 양천로11길 14','서울특별시 강서구 방화대로47가길 7','서울특별시 강서구 금낭화로 132','서울특별시 강서구 양천로 22']
group_2_ad = ['서울특별시 강서구 송정로4길 1-1']
group_3_ad = ['서울특별시 강서구 마곡중앙5로 6','서울특별시 강서구 마곡중앙5로 2']
group_4_ad = ['서울특별시 강서구 마곡중앙6로 85','서울특별시 강서구 강서로56나길 110','서울특별시 강서구 강서로 498','서울특별시 강서구 양천로 341','서울특별시 강서구 마곡중앙8로 90','서울특별시 강서구 양천로 341','서울특별시 강서구 강서로 399',
           '서울특별시 강서구 마곡동로4길 23','서울특별시 강서구 강서로 463','서울특별시 강서구 마곡중앙8로 86','서울특별시 강서구 강서로 471','서울특별시 강서구 강서로 395','서울특별시 강서구 공항대로 269-15','서울특별시 강서구 마곡중앙6로 89',
           '서울특별시 강서구 마곡중앙6로 93','서울특별시 강서구 강서로 443','서울특별시 강서구 마곡동로10길 23']
group_5_ad = ['서울특별시 강서구 양천로 564','서울특별시 강서구 양천로 492','서울특별시 강서구 허준로 198','서울특별시 강서구 양천로 560','서울특별시 강서구 양천로 485','서울특별시 강서구 화곡로68길 15','서울특별시 강서구 화곡로68길 15','서울특별시 강서구 양천로 570',
           '서울특별시 강서구 양천로 461','서울특별시 강서구 양천로 485','서울특별시 강서구 화곡로 404','서울특별시 강서구 양천로57길 13','서울특별시 강서구 양천로 560','서울특별시 강서구 양천로57길 9-19','서울특별시 강서구 양천로 551-17',
           '서울특별시 강서구 공항대로45길 44','서울특별시 강서구 허준로 139']

In [94]:
def grouping(ad_df):
  df = pd.DataFrame(columns = total_con.columns)
  for ad in ad_df:
    df = df.append(total_con[total_con.도로명주소 == ad])
  df = df.reset_index(drop=True)
  return df

group_1 = grouping(group_1_ad)
group_2 = grouping(group_2_ad)
group_3 = grouping(group_3_ad)
group_4 = grouping(group_4_ad)
group_5 = grouping(group_5_ad)

In [95]:
group_1

,상호명,지점명,단차/계단여부,확인가능여부,도로명주소,소재지면적,위도,경도
0,미니스톱,개화산역점,0,0,서울특별시 강서구 양천로 50,3.3,37.548870,126.878159
1,CU,방화행운점,1,0,서울특별시 강서구 방화대로45길 52,3.3,37.574454,126.813859
2,GS25,방화가온점,0,0,서울특별시 강서구 양천로11길 14,3.3,37.574781,126.809615
3,GS25,방화샤르망점,0,0,서울특별시 강서구 방화대로47가길 7,3.3,37.579957,126.814563
4,세븐일레븐,S방화역점,0,1,서울특별시 강서구 금낭화로 132,4.0,37.576190,126.812295
5,세븐일레븐,2872S개화산역점,0,1,서울특별시 강서구 양천로 22,6.6,37.548870,126.878159

- 세븐일레븐 S방화역점 & 세븐일레븐 287S개화산역점은 지하철 역사 내부에 위치한 편의점으로 거리뷰로 확인이 불가능하므로 제외함

In [96]:
group_2

,상호명,지점명,단차/계단여부,확인가능여부,도로명주소,소재지면적,위도,경도
0,세븐일레븐,강서공항점,1,0,서울특별시 강서구 송정로4길 1-1,3.3,37.558145,126.814114

In [97]:
group_3

,상호명,지점명,단차/계단여부,확인가능여부,도로명주소,소재지면적,위도,경도
0,CU,마곡보타닉푸르지오2호점,0,1,서울특별시 강서구 마곡중앙5로 6,3.3,37.567161,126.822005

In [99]:
group_4

,상호명,지점명,단차/계단여부,확인가능여부,도로명주소,소재지면적,위도,경도
0,GS25,마곡파크뷰점,0,0,서울특별시 강서구 마곡중앙6로 85,6.6,37.560340,126.833454
1,GS25,강서부영점,0,0,서울특별시 강서구 강서로56나길 110,6.6,37.564216,126.843656
2,CU,발산오피스점,0,1,서울특별시 강서구 마곡중앙8로 86,3.3,37.560900,126.836821
3,CU,마곡엠코점,0,0,서울특별시 강서구 강서로 471,4.0,37.559609,126.838587
4,CU,발산열린점,1,0,서울특별시 강서구 마곡중앙6로 93,3.3,37.560320,126.837949
5,CU,마곡투웨니점,0,0,서울특별시 강서구 강서로 443,6.7,37.559609,126.838587
6,세븐일레븐,마곡대방디엠,0,1,서울특별시 강서구 마곡동로10길 23,3.3,37.568684,126.838603

In [100]:
group_5

,상호명,지점명,단차/계단여부,확인가능여부,도로명주소,소재지면적,위도,경도
0,CU,등촌두산점,0,0,서울특별시 강서구 양천로 564,3.30,37.557135,126.861383
1,미니스톱,가양대교점,1,0,서울특별시 강서구 양천로 492,6.60,37.560898,126.854607
2,세븐일레븐,가양프라자점,0,0,서울특별시 강서구 허준로 198,6.60,37.565237,126.853576
3,CU,NH서울타워점,0,1,서울특별시 강서구 양천로 570,3.30,37.556549,126.862086
4,미니스톱,가양점,1,0,서울특별시 강서구 양천로 461,6.60,37.548870,126.878159
5,세븐일레븐,등촌스타점,1,0,서울특별시 강서구 화곡로 404,3.30,37.559269,126.854458
6,GS25,강서트레벨점,1,0,서울특별시 강서구 양천로57길 9-19,6.60,37.563808,126.852535
7,미니스톱,비즈메트로점,0,0,서울특별시 강서구 양천로 551-17,24.00,37.559169,126.860968
8,미니스톱,등촌청림점,1,0,서울특별시 강서구 공항대로45길 44,2.76,37.557508,126.856133
9,CU,가양3단지점,0,1,서울특별시 강서구 허준로 139,3.30,37.564450,126.855352

In [103]:
df_list[df_list['지점명'] == '강서공항점']

       상호명    지점명                도로명주소  단차/계단  확인불가
167  세븐일레븐  강서공항점  서울특별시 강서구 송정로4길 1-1      1     0
244   미니스톱  강서공항점  서울특별시 강서구 공항대로8길 55      0     1

### 소재지 면적 고려 X

In [104]:
df_list

       상호명       지점명                  도로명주소  단차/계단  확인불가
0       CU     강서태양점   서울특별시 강서구 강서로18길 146      1     0
1    세븐일레븐     화곡수명점   서울특별시 강서구 강서로33길 103      1     0
2    세븐일레븐   강서내발산길점   서울특별시 강서구 강서로45라길 35      0     0
3       CU     수명파크점    서울특별시 강서구 수명로1길 110      0     1
4       CU   마곡아르디에점      서울특별시 강서구 강서로 423      0     1
..     ...       ...                    ...    ...   ...
328     CU    가양3단지점      서울특별시 강서구 허준로 139      0     1
329   GS25  뉴마곡12단지점    서울특별시 강서구 마곡중앙1로 26      1     0
330     CU     화곡더숨점  서울특별시 강서구 초록마을로34길 57      1     0
331   GS25     화곡화원점   서울특별시 강서구 월정로30길 102      0     1
332   GS25     등촌월드점   서울특별시 강서구 공항대로39길 74      0     1

[333 rows x 5 columns]

In [107]:
def grouping(ad_df):
  df = pd.DataFrame(columns = df_list.columns)
  for ad in ad_df:
    df = df.append(df_list[df_list.도로명주소 == ad])
  df = df.reset_index(drop=True)
  return df

group_1 = grouping(group_1_ad)
group_2 = grouping(group_2_ad)
group_3 = grouping(group_3_ad)
group_4 = grouping(group_4_ad)
group_5 = grouping(group_5_ad)

In [111]:
group_4

      상호명        지점명                  도로명주소 단차/계단 확인불가
0    GS25     마곡파크뷰점    서울특별시 강서구 마곡중앙6로 85     0    0
1    GS25      강서부영점  서울특별시 강서구 강서로56나길 110     0    0
2      CU   SK가양주유소점      서울특별시 강서구 강서로 498     1    3
3      CU  906양천향교역점      서울특별시 강서구 양천로 341     0    2
4    GS25   S9양천향교역점      서울특별시 강서구 양천로 341     0    1
5    GS25    발산아이파크점    서울특별시 강서구 마곡중앙8로 90     0    1
6      CU  906양천향교역점      서울특별시 강서구 양천로 341     0    2
7    GS25   S9양천향교역점      서울특별시 강서구 양천로 341     0    1
8   세븐일레븐  마곡호서대기숙사점      서울특별시 강서구 강서로 399     0    0
9    GS25      마곡루체점    서울특별시 강서구 마곡동로4길 23     0    1
10  세븐일레븐     마곡신사고점      서울특별시 강서구 강서로 463     0    1
11     CU     발산오피스점    서울특별시 강서구 마곡중앙8로 86     0    1
12     CU      마곡엠코점      서울특별시 강서구 강서로 471     0    0
13   GS25    마곡플레이스점      서울특별시 강서구 강서로 395     0    1
14   GS25   마곡힐스테이트점  서울특별시 강서구 공항대로 269-15     0    0
15  이마트24      마곡골든점    서울특별시 강서구 마곡중앙6로 89     0    0
16     CU      발산열린점    서울특별시 강서구 마곡중앙6로 93     1    0
17     CU     마곡투웨니점      서울특별시 강서구 강서로 443     0    0
18  세븐일레븐     마곡대방디엠   서울특별시 강서구 마곡동로10길 23     0    1

In [112]:
group_5

      상호명      지점명                  도로명주소 단차/계단 확인불가
0      CU    등촌두산점      서울특별시 강서구 양천로 564     0    0
1    미니스톱    가양대교점      서울특별시 강서구 양천로 492     1    0
2   세븐일레븐   가양프라자점      서울특별시 강서구 허준로 198     0    0
3      CU  908증미역점      서울특별시 강서구 양천로 560     0    1
4    GS25   S9증미역점      서울특별시 강서구 양천로 560     0    0
5      CU  907가양역점      서울특별시 강서구 양천로 485     0    2
6    GS25   S9가양역점      서울특별시 강서구 양천로 485     0    0
7    GS25   가양테크노점    서울특별시 강서구 화곡로68길 15     0    1
8    GS25   가양테크노점    서울특별시 강서구 화곡로68길 15     0    1
9      CU  NH서울타워점      서울특별시 강서구 양천로 570     0    1
10   미니스톱      가양점      서울특별시 강서구 양천로 461     1    0
11     CU  907가양역점      서울특별시 강서구 양천로 485     0    2
12   GS25   S9가양역점      서울특별시 강서구 양천로 485     0    0
13  세븐일레븐    등촌스타점      서울특별시 강서구 화곡로 404     1    0
14     CU   가양휴먼빌점    서울특별시 강서구 양천로57길 13     0    0
15     CU  908증미역점      서울특별시 강서구 양천로 560     0    1
16   GS25   S9증미역점      서울특별시 강서구 양천로 560     0    0
17   GS25   강서트레벨점  서울특별시 강서구 양천로57길 9-19     1    0
18   미니스톱   비즈메트로점   서울특별시 강서구 양천로 551-17     0    0
19   미니스톱    등촌청림점   서울특별시 강서구 공항대로45길 44     1    0
20     CU   가양3단지점      서울특별시 강서구 허준로 139     0    1

In [130]:
rm = df_list[(df_list['확인불가'] == 3)].reset_index(drop=True).iloc[[2,4,5,6,7,8]]

In [122]:
temp = df_list[(df_list['확인불가'] == 0) | (df_list['확인불가'] == 3)]
temp = temp [temp['단차/계단'] == 1]
temp

       상호명       지점명                  도로명주소  단차/계단  확인불가
0       CU     강서태양점   서울특별시 강서구 강서로18길 146      1     0
1    세븐일레븐     화곡수명점   서울특별시 강서구 강서로33길 103      1     0
6       CU     우장산역점      서울특별시 강서구 강서로 251      1     0
8    세븐일레븐   화곡우장산숲점    서울특별시 강서구 화곡로31길 22      1     0
9     GS25     염창사랑점    서울특별시 강서구 양천로73길 80      1     0
..     ...       ...                    ...    ...   ...
314     CU      메트로점    서울특별시 강서구 화곡로26가길 2      1     0
316   GS25    발산에너지점    서울특별시 강서구 강서로56길 50      1     0
319     CU     화곡시원점  서울특별시 강서구 가로공원로76길 38      1     0
329   GS25  뉴마곡12단지점    서울특별시 강서구 마곡중앙1로 26      1     0
330     CU     화곡더숨점  서울특별시 강서구 초록마을로34길 57      1     0

[132 rows x 5 columns]

In [119]:
df_con

       상호명       지점명                  도로명주소          경도         위도
0       CU     강서태양점   서울특별시 강서구 강서로18길 146  126.852276  37.535197
1    세븐일레븐     화곡수명점   서울특별시 강서구 강서로33길 103  126.836783  37.541325
2    세븐일레븐   강서내발산길점   서울특별시 강서구 강서로45라길 35  126.834154  37.549464
3       CU     수명파크점    서울특별시 강서구 수명로1길 110  126.825508  37.553645
4       CU   마곡아르디에점      서울특별시 강서구 강서로 423  126.838587  37.559609
..     ...       ...                    ...         ...        ...
328     CU    가양3단지점      서울특별시 강서구 허준로 139  126.855352  37.564450
329   GS25  뉴마곡12단지점    서울특별시 강서구 마곡중앙1로 26  126.821870  37.558542
330     CU     화곡더숨점  서울특별시 강서구 초록마을로34길 57  126.845660  37.536928
331   GS25     화곡화원점   서울특별시 강서구 월정로30길 102  126.839170  37.534873
332   GS25     등촌월드점   서울특별시 강서구 공항대로39길 74  126.844576  37.561324

[333 rows x 5 columns]

In [136]:
me_df = pd.merge(temp, df_con, on=['도로명주소'], how='left')

In [140]:
final = me_df[['상호명_y','지점명_y','경도','위도']]
final.columns = ['상호명','지점명','경도','위도']

In [149]:
final[final.duplicated(['지점명'],keep=False)]

       상호명     지점명          경도         위도
60   세븐일레븐   화곡월정점  126.839170  37.534873
86      CU   화곡드림점  126.847237  37.538504
91    GS25   화곡드림점  126.849403  37.552314
94    GS25   화곡월정점  126.837860  37.534831
101   GS25  강서화곡로점  126.835969  37.538879
132  세븐일레븐  강서화곡로점  126.853233  37.557548

In [150]:
rm

     상호명       지점명                 도로명주소  단차/계단  확인불가
2     CU  SK가양주유소점     서울특별시 강서구 강서로 498      1     3
4     CU   910염창역점    서울특별시 강서구 공항대로 631      1     3
5   GS25       명덕점   서울특별시 강서구 강서로47길 36      1     3
6     CU      외발산점     서울특별시 강서구 방화대로 30      1     3
7   미니스톱     서울희망점   서울특별시 강서구 방화대로6길 33      1     3
8  세븐일레븐     화곡월정점  서울특별시 강서구 월정로30길 102      1     3